### ISSUE TITLE
[BUG]: Lockfile not cleaned up when closing terminal window abruptly

### ISSUE THREAD

**Issue by ljlamarche** [EarthCubeInGeo/resen#14] opened 2019-05-22 22:01 UTC
If I close the terminal window I'm running resen in WITHOUT using the `exit` command, the lock file is not deleted.  Then, next time I go to start resen, I get
```
ERROR: another instance of Resen is already running!
```
If I manually delete the lock file (~/.config/resen/lock on my system), I can start resen successfully.  While terminating programs by closing the shell running them probably isn't great practice, it's definitely something people do, so it would be nice if it were handled a little better.  Alternatively, we could have the instructions include directions for manually deleting the lock file if the user is sure that resen isn't running elsewhere on their system.

If I shut down my computer while I have a bucket still running, the bucket stops, but the resen tool doesn't track that it has stopped.  The json file doesn't change the status from "running" to "exited".  In the example below, bucket 2 was stopped with stop_bucket but bucket 3 was not.   This doesn't actually seem to break anything, but restart my computer and start resen again, the `status` command will still list that bucket as running even when it's not, which is somewhat confusing.
```

2 |  
-- | --
bucket |  
name | "davitpy3"
docker |  
image | "resenlab/davitpy-fix"
container | "8f83720e5a637dc730fe7e677f709295ae9c6bba6ca21834c961129cc50b17d2"
port |  
0 |  
0 | 8081
1 | 8001
2 | true
storage |  
0 |  
0 | "/Users/e30737/Desktop/Projects/InGeO/Resen/resen-core/resen-core/testing"
1 | "/home/jovyan/testing"
2 | "ro"
1 |  
0 | "/Users/e30737/Desktop/Projects/InGeO/Resen/EmptyResenTest2"
1 | "/home/jovyan/work/EmptyResenTest2"
2 | "rw"
status | "exited"
3 |  
bucket |  
name | "dockerhub"
docker |  
image | "docker.io/earthcubeingeo/resen-core:2019.1.0rc1"
container | "3324a0803c123e3fa9313cf87fd82e42f23eaaf311791ceaecd69f40a586521d"
port |  
0 |  
0 | 8080
1 | 8000
2 | true
storage |  
0 |  
0 | "/Users/e30737/Desktop/Projects/InGeO/Resen/resen-core/resen-core/testing"
1 | "/home/jovyan/work/testing"
2 | "ro"
status | "running"

```

**Comment by pmreyes2** [comment] 2019-05-22 22:31
1. To avoid the lock file to remain after manually closing the terminal window: Maybe there is a way to detect the "closing terminal window" action and exit the resen tool gracefully?
2. When starting the resen tool, there could be some docker commands to check if a container exists, and if it is running or not and correct/update the json file.

**Comment by asreimer** [comment] 2019-05-24 04:21
1. The simplest solution might be to use [atexit](https://docs.python.org/3.2/library/atexit.html). Another thing to do is to write the PID of the current python process into the lock file, then check to see if the lockfile exists and if is exists check to see if the PID in it belongs to an existing python process. If not, it's probably safe to ignore the lock file. Ideally, `atexit` will fix everything.

2. This was already listed as a [`TODO`](https://github.com/EarthCubeInGeo/resen/blob/master/resen/Resen.py#L125). It should be easy to fix since there's already an update method included in the `BucketManager` class, called [update_bucket_statuses](https://github.com/EarthCubeInGeo/resen/blob/master/resen/Resen.py#L563-L572). So all that needs to happen is that the update method needs to be called after the `load_config()` method. Probably [after this line](https://github.com/EarthCubeInGeo/resen/blob/master/resen/Resen.py#L136).

**Comment by asreimer** [comment] 2019-06-06 20:21
Labelling as a bug, because [expected behaviour is violated here](https://en.wikipedia.org/wiki/Principle_of_least_astonishment).

**Comment by asreimer** [comment] 2019-06-06 20:23
Note that a similar problem will occur if someones computer is shutdown abruptly. `atexit` will not fix this problem for the power outage edge case.

**Comment by asreimer** [comment] 2019-06-07 06:53
`atexit` doesn't help us at all. At least, not the way I implemented it. Tried running this:

    python lock.py

This creates a 'testing.lock' file in the current working directory. The contents of lock.py is:

    import os
    import atexit

    class App():
        def __init__(self):
            self.__locked = False
            self.__lock()

        def __lock(self):
            self.__lockfile = 'testing.lock'
            # check if lock file exists
            if os.path.exists(self.__lockfile):
                raise RuntimeError('Lockfile')
            with open(self.__lockfile,'w') as f:
                f.write('')
            self.__locked = True

        def _unlock(self):
            if not self.__locked:
                return
            try:
                os.remove(self.__lockfile)
                self.__locked = False
            except FileNotFoundError:
                # should never happen...
                pass
            except Exception as e:
                print("WARNING: Unable to remove lockfile: %s" % str(e))
    
    if __name__ == '__main__':
        app = App()
        atexit.register(app._unlock)
        while True:
            pass

then close the terminal window and check to see if the "testing.lock" file still exists.

**Comment by asreimer** [comment] 2019-06-07 06:55
Creating a lock file and then using file locking might work, as long as the file lock is released when the terminal window is closed. This appears to be a good cross-platform working example: https://www.oreilly.com/library/view/python-cookbook/0596001673/ch04s25.html

I've checked, and the win32* packages exist on an anaconda installation in Windows.

**Comment by asreimer** [comment] 2020-11-06 05:35
I've implemented a fix for this that writes the PID of the running process to the lockfile. When another instance of Resen is instantiated, it checks for a process with the PID in the existing lockfile. If that doesn't exist, then we can assume the previous instance crashed and didn't clean up after itself.

There are more advanced things we can do if we see problems, but for now this seems to fix things nicely.

**Closed as completed** 2020-11-06 19:34 UTC
Labels: bug, discussion
